name: login
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  path: ^1.9.1
  # path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
